name: CI/CD - Docker Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm run test

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dynadok:latest -f docker/Dockerfile .

      - name: Push para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dynadok:latest

  deploy:
    needs: test-build-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH para o servidor e pull da imagem
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dynadok:latest
            docker stop dynadok-api || true
            docker rm dynadok-api || true
            docker run -d --name dynadok-api -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/dynadok:latest
